### ISSUE TITLE
Add link to location on OSM

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary-chrome-extension#2]
As suggested on a comment on the [blog post](http://blog.mapillary.com/update/2016/05/30/mapillary-chrome-extension.html), it'd be nice to have a link to open the OSM map on the location. Perhaps just changing the OSM attribution link to be to openstreetmap.org/_coordinates_.

**Comment by gyllen** [comment]
@nickplesha Is this easy todo?

**Comment by nickplesha** [comment]
Hi! Yes, this would be easy to do. I'll update the map component for the next version.
Goals: 
- Give users clear feedback what is going to happen when the map is clicked.
- Give users the option to go to the OSM map at the location coordinates.

**Comment by Caboosey** [comment]
@gyllen @nickplesha I will try to take look into this. :) You can co-assign me if you want.

**Comment by nickplesha** [comment]
Clicking on the `OpenStreetMap` attribution in the mini-map now takes you to the exact image location in OSM ready for editing. :)
