### ISSUE TITLE
Feedback (Random images and image quality)

### ISSUE THREAD

**Issue by Jolg42** [mapillary/mapillary-chrome-extension#7]
Hi,

I'm using the extension on my Chrome browser, I like it ❤️  but I noticed that it's the same places showing up. Is it possible to have a true random place each time or a lot more places?

Also the quality of the images is important so I don't know if it's possible to select only large high definition images?

**Comment by nickplesha** [comment]
The nature of true randomness is that it can happen that the same image pops up ten times in a row. :) As the image selection increases, this situation should be less likely. We updated the list to include only high definition images and we'll continue to update it and expand it continuously.
